In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

from steinberg_utils_3vertex import *

Verification of the formula in 

Eigenvalue sampling

In [148]:
signal = [3,5,7]
tau = np.around(np.arange(0.01,2.0,step=.01), decimals = 2)
alpha = 1
beta = 3

In [149]:
params = [134.893, 0.005, 34.320, 0.041, 12.775, 149.760]
#params = [11.781, 0.291, 17.519, 0.013, 0.006, 542.228]
print(cycle_affinity_K(params))
L = Laplacian_K(params)
eigvals, left_eigvecs, right_eigvecs = scipy.linalg.eig(L, left=True, right=True)
eigvals

19.394254601663402


array([-8.62161517e-17 +0.j       , -1.65897000e+02+53.7992314j,
       -1.65897000e+02-53.7992314j])

In [150]:
L

array([[-1.47668e+02,  5.00000e-03,  1.49760e+02],
       [ 1.34893e+02, -3.43250e+01,  4.10000e-02],
       [ 1.27750e+01,  3.43200e+01, -1.49801e+02]], dtype=float128)

In [151]:
params

[134.893, 0.005, 34.32, 0.041, 12.775, 149.76]

In [163]:
idx_1 = np.argmax(eigvals)
idx_1

0

In [164]:
lambda_1 = eigvals[idx_1]
z_1 = right_eigvecs[:,idx_1]
w_1 = left_eigvecs[:,idx_1]

In [165]:
# Normalize u_1 and v_1
normalization_1 = sum(z_1)
z_1 = z_1/normalization_1
w_1 = w_1/w_1

In [166]:
eigvals_other = np.delete(eigvals, idx_1)
eigvals_other

array([-165.897+53.7992314j, -165.897-53.7992314j])

In [167]:
# Delete eigenvectors u_1 and v_1 from their respective arrays
right_eigvecs_other = np.delete(right_eigvecs, idx_1, axis=1)
left_eigvecs_other = np.delete(left_eigvecs, idx_1, axis=1)

In [168]:
idx_3 = np.argmin(eigvals_other)
idx_2 = np.argmax(eigvals_other)
idx_2

0

In [175]:
# Define lambda_2 and lambda_3
lambda_2 = eigvals_other[idx_2]
lambda_3 = eigvals_other[idx_3]
lambda_2

(-165.89699999999993+53.79923139785545j)

In [ ]:
# Define left and right eigenvectors for lambda_2 and normalize appropriately
z_2 = right_eigvecs_other[:,idx_2]
w_2 = left_eigvecs_other[:,idx_2]
w_2

array([-0.09810327-0.32810973j, -0.20409513+0.0834661j ,
        0.91328984+0.j        ])

In [178]:
# Define left and right eigenvectors for lambda_3 and normalize appropriately
z_3 = right_eigvecs_other[:,idx_3]
w_3 = left_eigvecs_other[:,idx_3]
w_3

array([-0.09810327+0.32810973j, -0.20409513-0.0834661j ,
        0.91328984-0.j        ])

In [179]:
np.dot(w_2,z_3)

(-0.041942757247648704-0.5614998938183421j)

In [183]:
np.dot(w_3,z_2)

(-0.041942757247648704+0.5614998938183421j)

In [182]:
w_2[0]*z_3[0]

(-0.06861287069531473-0.2294780917153401j)

In [136]:
w_2[1]

-0.7279275445959555

In [137]:
z_3[1]

0.01605678148238229

In [138]:
-0.7279275445959555 * 0.01605678148238229

-0.011688173518584347

How does the area formula break down when the eigenvalues are complex?

In [21]:
# complex parameter set
params = [134.893, 0.005, 34.320, 0.041, 12.775, 149.760]

# real parameter set
#params = [11.781, 0.291, 17.519, 0.013, 0.006, 542.228]

In [22]:
L = Laplacian_K(params)
L

array([[-1.47668e+02,  5.00000e-03,  1.49760e+02],
       [ 1.34893e+02, -3.43250e+01,  4.10000e-02],
       [ 1.27750e+01,  3.43200e+01, -1.49801e+02]], dtype=float128)

In [45]:
eigvals, left_eigvecs, right_eigvecs = scipy.linalg.eig(L, left=True, right=True)
print(eigvals)
lambda_1 = eigvals[0]
lambda_2 = eigvals[1]
lambda_3 = eigvals[2]

print(lambda_1)
print(lambda_2)
print(lambda_3)

[-8.62161517e-17 +0.j        -1.65897000e+02+53.7992314j
 -1.65897000e+02-53.7992314j]
(-8.621615171411029e-17+0j)
(-165.89699999999993+53.79923139785545j)
(-165.89699999999993-53.79923139785545j)


In [46]:
print(left_eigvecs)

[[ 0.57735027+0.j         -0.09810327-0.32810973j -0.09810327+0.32810973j]
 [ 0.57735027+0.j         -0.20409513+0.0834661j  -0.20409513-0.0834661j ]
 [ 0.57735027+0.j          0.91328984+0.j          0.91328984-0.j        ]]


In [47]:
print(right_eigvecs)

[[ 0.23955836+0.j          0.69939434+0.j          0.69939434-0.j        ]
 [ 0.94171681+0.j         -0.61428358-0.25125624j -0.61428358+0.25125624j]
 [ 0.23618053+0.j         -0.08511076+0.25125624j -0.08511076-0.25125624j]]


In [24]:
idx_1 = np.argmax(eigvals)
idx_1

0

In [25]:
z_1 = right_eigvecs[:,idx_1]
w_1 = left_eigvecs[:,idx_1]

In [26]:
# Normalize u_1 and v_1
normalization_1 = sum(z_1)
z_1 = z_1/normalization_1
w_1 = w_1/w_1

In [27]:
eigvals_other = np.delete(eigvals, idx_1)
eigvals_other

array([-165.897+53.7992314j, -165.897-53.7992314j])

In [28]:
# Delete eigenvectors u_1 and v_1 from their respective arrays
right_eigvecs_other = np.delete(right_eigvecs, idx_1, axis=1)
left_eigvecs_other = np.delete(left_eigvecs, idx_1, axis=1)

In [29]:
idx_3 = np.argmin(eigvals_other)
idx_2 = np.argmax(eigvals_other)
idx_2

0

In [31]:
# Define lambda_2 and lambda_3
lambda_2 = eigvals_other[idx_2]
lambda_3 = eigvals_other[idx_3]
print(lambda_2)
print(lambda_3)

(-165.89699999999993+53.79923139785545j)
(-165.89699999999993-53.79923139785545j)


In [32]:
# Define left and right eigenvectors for lambda_2 and normalize appropriately
z_2 = right_eigvecs_other[:,idx_2]
w_2 = left_eigvecs_other[:,idx_2]
print(z_2)
print(w_2)

[ 0.69939434+0.j         -0.61428358-0.25125624j -0.08511076+0.25125624j]
[-0.09810327-0.32810973j -0.20409513+0.0834661j   0.91328984+0.j        ]


In [35]:
np.dot(L,z_2)

array([-116.02742334+37.6268781j ,  115.42519542 +8.63467192j,
          0.60222791-46.26155002j], dtype=complex256)

In [34]:
lambda_2*z_2

array([-116.02742334+37.6268781j ,  115.42519542 +8.63467192j,
          0.60222791-46.26155002j])

In [49]:
np.dot(w_3,L)

array([  -1.37701364-59.71030092j,   38.34918235 +2.86661446j,
       -151.51204516+49.13429162j], dtype=complex256)

In [48]:
lambda_2*w_3

array([  -1.37701364-59.71030092j,   38.34918235 +2.86661446j,
       -151.51204516+49.13429162j])

In [14]:
# Define left and right eigenvectors for lambda_3 and normalize appropriately
z_3 = right_eigvecs_other[:,idx_3]
w_3 = left_eigvecs_other[:,idx_3]
w_3

array([-0.09810327+0.32810973j, -0.20409513-0.0834661j ,
        0.91328984-0.j        ])

In [50]:
np.dot(w_3,z_3)

(8.673617379884035e-17-1.1102230246251565e-16j)

In [51]:
np.dot(w_2,z_2)

(8.673617379884035e-17+1.1102230246251565e-16j)

In [17]:
w_2[0]*z_3[0]

(-0.06861287069531473-0.2294780917153401j)

In [18]:
w_2[1]

(-0.20409513294365542+0.08346610094154272j)

In [19]:
z_3[1]

(-0.6142835787877554+0.25125623920676676j)

In [20]:
-0.7279275445959555 * 0.01605678148238229

-0.011688173518584347

Eigenvalue sampling

In [148]:
signal = [3,5,7]
tau = np.around(np.arange(0.01,2.0,step=.01), decimals = 2)
alpha = 1
beta = 3

In [149]:
params = [134.893, 0.005, 34.320, 0.041, 12.775, 149.760]
#params = [11.781, 0.291, 17.519, 0.013, 0.006, 542.228]
print(cycle_affinity_K(params))
L = Laplacian_K(params)
eigvals, left_eigvecs, right_eigvecs = scipy.linalg.eig(L, left=True, right=True)
eigvals

19.394254601663402


array([-8.62161517e-17 +0.j       , -1.65897000e+02+53.7992314j,
       -1.65897000e+02-53.7992314j])

In [150]:
L

array([[-1.47668e+02,  5.00000e-03,  1.49760e+02],
       [ 1.34893e+02, -3.43250e+01,  4.10000e-02],
       [ 1.27750e+01,  3.43200e+01, -1.49801e+02]], dtype=float128)

In [151]:
params

[134.893, 0.005, 34.32, 0.041, 12.775, 149.76]

In [163]:
idx_1 = np.argmax(eigvals)
idx_1

0

In [164]:
lambda_1 = eigvals[idx_1]
z_1 = right_eigvecs[:,idx_1]
w_1 = left_eigvecs[:,idx_1]

In [165]:
# Normalize u_1 and v_1
normalization_1 = sum(z_1)
z_1 = z_1/normalization_1
w_1 = w_1/w_1

In [166]:
eigvals_other = np.delete(eigvals, idx_1)
eigvals_other

array([-165.897+53.7992314j, -165.897-53.7992314j])

In [167]:
# Delete eigenvectors u_1 and v_1 from their respective arrays
right_eigvecs_other = np.delete(right_eigvecs, idx_1, axis=1)
left_eigvecs_other = np.delete(left_eigvecs, idx_1, axis=1)

In [168]:
idx_3 = np.argmin(eigvals_other)
idx_2 = np.argmax(eigvals_other)
idx_2

0

In [175]:
# Define lambda_2 and lambda_3
lambda_2 = eigvals_other[idx_2]
lambda_3 = eigvals_other[idx_3]
lambda_2

(-165.89699999999993+53.79923139785545j)

In [ ]:
# Define left and right eigenvectors for lambda_2 and normalize appropriately
z_2 = right_eigvecs_other[:,idx_2]
w_2 = left_eigvecs_other[:,idx_2]
w_2

array([-0.09810327-0.32810973j, -0.20409513+0.0834661j ,
        0.91328984+0.j        ])

In [178]:
# Define left and right eigenvectors for lambda_3 and normalize appropriately
z_3 = right_eigvecs_other[:,idx_3]
w_3 = left_eigvecs_other[:,idx_3]
w_3

array([-0.09810327+0.32810973j, -0.20409513-0.0834661j ,
        0.91328984-0.j        ])

In [179]:
np.dot(w_2,z_3)

(-0.041942757247648704-0.5614998938183421j)

In [183]:
np.dot(w_3,z_2)

(-0.041942757247648704+0.5614998938183421j)

In [182]:
w_2[0]*z_3[0]

(-0.06861287069531473-0.2294780917153401j)

In [136]:
w_2[1]

-0.7279275445959555

In [137]:
z_3[1]

0.01605678148238229

In [138]:
-0.7279275445959555 * 0.01605678148238229

-0.011688173518584347